# Generated by Django 3.2.7 on 2021-09-12 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid', models.CharField(max_length=128, unique=True)),
                ('ikm_key', models.CharField(max_length=256)),
                ('timestamp', models.BigIntegerField()),
                ('lifetime', models.IntegerField()),
                ('as_rs_alg', models.CharField(max_length=64)),
                ('realm', models.CharField(max_length=127)),
            ],
            options={
                'db_table': 'oauth_key',
            },
        ),
        migrations.CreateModel(
            name='TurnOriginToRealm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=127, unique=True)),
                ('realm', models.CharField(max_length=127)),
            ],
            options={
                'db_table': 'turn_origin_to_realm',
            },
        ),
        migrations.CreateModel(
            name='TurnSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm', models.CharField(max_length=127)),
                ('value', models.CharField(max_length=127)),
            ],
            options={
                'db_table': 'turn_secret',
            },
        ),
        migrations.CreateModel(
            name='TurnUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm', models.CharField(blank=True, default='', max_length=127)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('hmackey', models.CharField(blank=True, max_length=128, null=True)),
                ('django_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coturn_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'turnusers_lt',
            },
        ),
        migrations.CreateModel(
            name='TurnRealmOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm', models.CharField(blank=True, max_length=127, null=True)),
                ('opt', models.CharField(blank=True, max_length=32, null=True)),
                ('value', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'turn_realm_option',
                'unique_together': {('realm', 'opt')},
            },
        ),
        migrations.CreateModel(
            name='DeniedPeerIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm', models.CharField(blank=True, max_length=127, null=True)),
                ('ip_range', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'denied_peer_ip',
                'unique_together': {('realm', 'ip_range')},
            },
        ),
        migrations.CreateModel(
            name='AllowedPeerIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm', models.CharField(blank=True, max_length=127, null=True)),
                ('ip_range', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'allowed_peer_ip',
                'unique_together': {('realm', 'ip_range')},
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('realm', models.CharField(blank=True, max_length=127, null=True)),
                ('password', models.CharField(blank=True, max_length=127, null=True)),
                ('django_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coturn_admin_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_user',
            },
        ),
    ]
